### PR TITLE
Graphing and data retention

### PR DESCRIPTION
**Pull request by joeandaverde**
Opening this PR to begin discussion.

I think the data will need to be summarized by the minute to avoid plotting too many points and slowing render time. I plan on displaying the graph using a raspberry pi.

image

### CODE REVIEW

**Comment by Aenima4six2** [comment]
Love this. I’ll take a deeper look tomorrow.

**Comment by joeandaverde** [comment]
I didn't check in the package-lock.json because of so many changes. Maybe my configuration is off because it changed all dependencies to exact.

**Comment by Aenima4six2** [comment]
What version of npm are you running? There was an open bug in the 5.x builds that caused this.

**Comment by Aenima4six2** [comment]
Also, I pushed up an `emulator` not too long ago to make this type of testing easier.

**Comment by Aenima4six2** [comment]
On another note, once we have some historical data in the db, we could use some simple regression to forecast the time to hit desired temps. I'm going to push up a branch of various fixes, then I can jump on this branch with you, if you need any help.

**Comment by joeandaverde** [comment]
npm 5.5.1

Sounds fun (to collaborate)!  We could start a google meet to discuss or a slack channel or just stick to these comments.

**Comment by joeandaverde** [comment]
A few other thoughts I had:

- It would be nice to also plot the desired temperature as a dashed line. 
- Having the ability to add a note at a specific time by clicking on the chart. Say, wrapped the meat with tin-foil.
- A state machine to do the profiles like in the app.

**Comment by Aenima4six2** [comment]
Absolutely, I'll send you a slack invite. Also, upgrade to npm 6.x when you get time.

**Pull request merged**
